// <auto-generated />
using System;
using GameStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStore.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    [Migration("20240131224220_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("GameStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Catagories")
                        .HasColumnType("TEXT");

                    b.Property<string>("Developer")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageGame")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Review")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Catagories = "Action, Adventure, RPG",
                            Developer = "Ubisoft Montreal",
                            DiscountPercentage = 15m,
                            ImageGame = "/public/call of duty.jpeg",
                            Name = "Call Of Duty",
                            Price = 59.99m,
                            Publisher = "Ubisoft",
                            ReleaseDate = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = "242,544"
                        },
                        new
                        {
                            Id = 2,
                            Catagories = "Action, RPG",
                            Developer = "CD Projekt",
                            DiscountPercentage = 10m,
                            ImageGame = "/public/dead space.jpeg",
                            Name = "Dead Space",
                            Price = 49.99m,
                            Publisher = "CD Projekt",
                            ReleaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = "345,542"
                        },
                        new
                        {
                            Id = 3,
                            Catagories = "Action, RPG",
                            Developer = "CD Projekt",
                            DiscountPercentage = 20m,
                            ImageGame = "/public/duty after school.jpeg",
                            Name = "Duty After School",
                            Price = 29.99m,
                            Publisher = "CD Projekt",
                            ReleaseDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = "Very Positive"
                        },
                        new
                        {
                            Id = 4,
                            Catagories = "Sports, Simulation",
                            Developer = "EA Vancouver",
                            DiscountPercentage = 10m,
                            ImageGame = "/public/Enshrounded.jpeg",
                            Name = "Enshrounded",
                            Price = 39.99m,
                            Publisher = "Electronic Arts",
                            ReleaseDate = new DateTime(2021, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = "Positive"
                        },
                        new
                        {
                            Id = 5,
                            Catagories = "Action, Adventure",
                            Developer = "Rockstar Studios",
                            DiscountPercentage = 15m,
                            ImageGame = "/public/God Of War.jpeg",
                            Name = "God Of War",
                            Price = 69.99m,
                            Publisher = "Rockstar Games",
                            ReleaseDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = "Very Positive"
                        },
                        new
                        {
                            Id = 6,
                            Catagories = "Action, Shooter",
                            Developer = "Infinity Ward",
                            DiscountPercentage = 10m,
                            ImageGame = "/public/hogwart.jepg",
                            Name = "Hogwart",
                            Price = 49.99m,
                            Publisher = "Activision",
                            ReleaseDate = new DateTime(2019, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = "Positive"
                        },
                        new
                        {
                            Id = 7,
                            Catagories = "Sandbox, Adventure",
                            Developer = "Mojang Studios",
                            DiscountPercentage = 25m,
                            ImageGame = "/public/knivea out.jpeg",
                            Name = "Knivea Out",
                            Price = 19.99m,
                            Publisher = "Mojang",
                            ReleaseDate = new DateTime(2011, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = "Overwhelmingly Positive"
                        },
                        new
                        {
                            Id = 8,
                            Catagories = "Casual, Party Game",
                            Developer = "InnerSloth",
                            DiscountPercentage = 50m,
                            ImageGame = "/public/League Legend.jpeg",
                            Name = "League Legend",
                            Price = 4.99m,
                            Publisher = "InnerSloth",
                            ReleaseDate = new DateTime(2018, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = "Very Positive"
                        },
                        new
                        {
                            Id = 9,
                            Catagories = "MOBA",
                            Developer = "Riot Games",
                            DiscountPercentage = 0m,
                            ImageGame = "/public/Palworld.jpeg",
                            Name = "Palworld",
                            Price = 0m,
                            Publisher = "Riot Games",
                            ReleaseDate = new DateTime(2009, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = "Very Positive"
                        },
                        new
                        {
                            Id = 10,
                            Catagories = "Action, Shooter",
                            Developer = "id Software",
                            DiscountPercentage = 20m,
                            ImageGame = "/public/TEKKEN 8.jpeg",
                            Name = "TEKKEN 8",
                            Price = 59.99m,
                            Publisher = "Bethesda Softworks",
                            ReleaseDate = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = "Very Positive"
                        },
                        new
                        {
                            Id = 11,
                            Catagories = "Action, Shooter",
                            Developer = "id Software",
                            DiscountPercentage = 20m,
                            ImageGame = "/public/tntm.jpeg",
                            Name = "Till The End Of The Moonl",
                            Price = 59.99m,
                            Publisher = "Bethesda Softworks",
                            ReleaseDate = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = "21,543"
                        },
                        new
                        {
                            Id = 12,
                            Catagories = "Action, Shooter",
                            Developer = "id Software",
                            DiscountPercentage = 20m,
                            ImageGame = "/public/Tom Clancy's Rainbow.jpeg",
                            Name = "Tom Clancy's Rainbow",
                            Price = 59.99m,
                            Publisher = "Bethesda Softworks",
                            ReleaseDate = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = "876,234"
                        },
                        new
                        {
                            Id = 13,
                            Catagories = "Action, Shooter",
                            Developer = "id Software",
                            DiscountPercentage = 20m,
                            ImageGame = "/public/War Thunder.jpeg",
                            Name = "War Thunderl",
                            Price = 59.99m,
                            Publisher = "Bethesda Softworks",
                            ReleaseDate = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = "143,756"
                        },
                        new
                        {
                            Id = 14,
                            Catagories = "Action, Shooter",
                            Developer = "id Software",
                            DiscountPercentage = 20m,
                            ImageGame = "/public/World of Tanks.jpeg",
                            Name = "World of Tanks",
                            Price = 59.99m,
                            Publisher = "Bethesda Softworks",
                            ReleaseDate = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Review = "566,34"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
